--- 
javascripts:
- admin:
  - prototype
  - effects
  - controls
  - dragdrop
  - application
- application:
  - application
stylesheets:
- new_layout:
  - reset
  - new_layout
- admin:
  - screen
  - application
- application:
  - screen
  - application
- ie:
  - ie