--- 
development: 
  base_uri: http://localhost:3001
  application_name: test
  protect_paths: &id001 
    - ^/api/
defaults: 
  base_uri: http://localhost:3001
  application_name: test
  protect_paths: *id001
cucumber: 
  base_uri: http://localhost:3001
  application_name: test
  protect_paths: *id001
test: 
  base_uri: http://localhost:3001
  application_name: test
  protect_paths: 
  - ^/api/
  - ^/foo/bar/
  - /lookup/?$
